# Chaining

[Promise/A+: The `then` Method](https://promisesaplus.com/#point-40)

`then` 必须返回一个 `promise`，如

```js
promise2 = promise1.then(onFulfilled, onRejected);
```

并且 `promise2` 产生的过程必须符合，

- 如果 `onFulfilled` 或者 `onRejected` 返回了值 `x`，必须走 `[[Resolve]](promise2, x)` 过程
- 如果 `onFulfilled` 或者 `onRejected` 抛出异常 `e`，`promise2` 以 `rejected` 状态接收 `e` 作为 `reason`
- 如果 `onFulfilled` 不是函数且 `promise1` 的状态是 `fullfilled`，`promise2` 必须以 `fulfilled` 状态接收 `promise1` 的 `value`
- 如果 `onRejected` 不是函数且 `promise1` 的状态是 `rejected`，`promise2` 必须以 `rejected` 状态接收 `promise1` 的 `reason`

先看后 3 个

```js
describe("Chaining", () => {
  test(".then should return a promise", () => {
    const p1 = new Promise((resolve, reject) => {
      resolve(1);
    });
    const p2 = p1.then();
    expect(p2).toBeInstanceOf(Promise);
  });
  test("If onFulfilled is not a function and promise1 is fulfilled, promise2 must be fulfilled with the same value as promise1.", (done) => {
    const p1 = new Promise((resolve, reject) => {
      resolve(1);
    });
    const p2 = p1.then();
    setTimeout(() => {
      expect(p2.state).toBe("fulfilled");
      expect(p2.value).toBe(1);
      done();
    });
  });
  test("If onRejected is not a function and promise1 is rejected, promise2 must be rejected with the same reason as promise1.", (done) => {
    const p1 = new Promise((resolve, reject) => {
      reject(1);
    });
    const p2 = p1.then();
    setTimeout(() => {
      expect(p2.state).toBe("rejected");
      expect(p2.reason).toBe(1);
      done();
    });
  });
  test("If onFulfilled throws an exception e, promise2 must be rejected with e as the reason.", (done) => {
    const p1 = new Promise((resolve, reject) => {
      resolve(1);
    });
    const onFulfilled = () => {
      throw "e";
    };
    const p2 = p1.then(onFulfilled);
    setTimeout(() => {
      expect(p2.state).toBe("rejected");
      expect(p2.reason).toBe("e");
      done();
    });
  });
  test("If onRejected throws an exception e, promise2 must be rejected with e as the reason.", (done) => {
    const p1 = new Promise((resolve, reject) => {
      reject(1);
    });
    const onRejected = () => {
      throw "e";
    };
    const p2 = p1.then(null, onRejected);
    setTimeout(() => {
      expect(p2.state).toBe("rejected");
      expect(p2.reason).toBe("e");
      done();
    });
  });
});
```

根据要求，`.then` 方法必须返回一个新的 `promise2` 对象，

```js
then(onFulfilled, onRejected) {
    const promise2 = new Promise((resolve, reject) => {
        handle(this, { onFulfilled, onRejected }, resolve, reject);
    });
    return promise2;
}
```

因为 `promise2` 的状态和值都依赖于初始的 `this` 这个 `promise`。所以所有对 `promise2` 的操作都应给嵌入到 `handle` 函数里面去。

```js
const handle = (promise, handler, resolve, reject) => {
  if (promise.state === FULFILLED) {
    if (typeof handler.onFulfilled === "function") {
      setTimeout(() => {
        try {
          resolve(handler.onFulfilled(promise.value));
        } catch (error) {
          reject(error);
        }
      });
    } else {
      resolve(promise.value);
    }
  }
  if (promise.state === REJECTED) {
    if (typeof handler.onRejected === "function") {
      setTimeout(() => {
        try {
          reject(handler.onRejected(promise.reason));
        } catch (error) {
          reject(error);
        }
      });
    } else {
      reject(promise.reason);
    }
  }
  if (promise.state === PENDING) {
    promise.onFulfilledQueue.push((value) =>
      setTimeout(() => handler.onFulfilled(value))
    );
    promise.onRejectedQueue.push((reason) =>
      setTimeout(() => handler.onRejected(reason))
    );
  }
};
```

最后看第一个，这里描述了一个抽象过程 `[[Resolve]](promise2, x)`

- 如果 `promise2` 和 `x` 指向同一个对象，则 `promise2` 必须报 `TypeError` 错误
- 如果 `x` 是 `promise` 对象，则 `promise2` 采用 `x` 的状态和值
- 如果 `x` 是一个对象或者方程
- 除以上情形（说明 `x` 是个基本类型），让 `promise2` 为 `fulfilled` 状态，值为 `x`
